#!/bin/bash
#
# Description : Contrôle SPIP à la ligne de commande. Doit être exécuté depuis
# la racine d'un site spip.
#
# Usage : spipsh [COMMAND]
#
# Options :
#
# %% all
# desc="Permet de vider aussi le cache des vignettes. Valable uniquement pour la commande cc."
# short="a" variable="all" value="1" default=0
#
# %% dry-run
# desc="Ne pas exécuter les commandes, seulement les afficher."
# short="d" variable="dry_run" value=1 default=0
#
# %% connect
# desc="Permet de choisir un fichier connect.php alternatif."
# short="c" variable="connect" default="connect"
#
# %% tmp-dir
# desc="Permet de choisir un répertoire tmp/ alternatif."
# short="t" variable="tmp_dir" default="tmp"
#
# %% local-dir
# desc="Permet de choisir un répertoire local/ alternatif."
# short="l" variable="local_dir" default="local"
#
set -euo pipefail

# shellcheck disable=SC2034
term_width=80

script_dir="$(dirname "$(readlink -f "$0")")"

# charger les fichiers du dossier lib/
# shellcheck source=/dev/null
. <(cat "${script_dir}"/lib/*.sh)

# shellcheck disable=SC2068
opt_parse $@

# shellcheck disable=2154
if [[ ! -f "config/$connect.php" ]]; then
    out_usage_error "config/$connect.php n'est pas un fichier."
fi

# shellcheck disable=2154
if [[ ! -d "$tmp_dir" ]]; then
    out_usage_error "$tmp_dir n'est pas un dossier."
fi

# shellcheck disable=2154
if [[ ! -d "$local_dir" ]]; then
    out_usage_error "$local_dir n'est pas un dossier."
fi


# commande par défaut
if [[ -z "${1+x}" ]]; then
    cmd="help";
fi

if _cmds_is_registered "$cmd" && [[ $( _meta_command_get "$cmd" "env" ) == 'spip' ]]; then
    _spip_get_env;
fi;

if [[ -f "${cmd_file:=${script_dir}/cmd/$cmd.sh}" ]]; then
    # shellcheck source=/dev/null
    . "$cmd_file"
else
    _help_print
fi
